kind: Pod
apiVersion: v1
metadata:
  name: storage-pod
spec:
  containers:
    - name: bash
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: data-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: storage-pvc # defined in csi-pvc.yaml
