apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: oksanazh/paymentservice:v0.0.1
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
#        readinessProbe:
#          exec:
#            command: ["/bin/grpc_health_probe", "-addr=:50051"]
#        livenessProbe:
#          exec:
#            command: ["/bin/grpc_health_probe", "-addr=:50051"]
#        resources:
#          requests:
#            cpu: 100m
#           memory: 64Mi
#          limits:
#            cpu: 200m
#            memory: 128Mi

