prometheusOperator:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool

prometheus:
  prometheusSpec:
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
    nodeSelector:
      cloud.google.com/gke-nodepool: infra-pool
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
    nodeSelector:
      cloud.google.com/gke-nodepool: infra-pool

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
       - grafana.34.136.166.110.nip.io
    path: /

  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool

  additionalDataSources:
    name: Loki
    type: Loki
    url: http://loki:3100/
    access: direct


prometheus-node-exporter:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool

kube-state-metrics:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool